name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Tests
        run: |
          make test
